item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path ('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='details'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

messaging/urls.py
from django.urls import path

from .import views
app_name = 'messaging'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_message, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('', views.inbox, name='inbox'),
]

storefront/urls.py
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar  # type: ignore
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),    
    path('items/', include('item.urls')), 
    path('dashboard/', include('dashboard.urls')),
    path('messaging/', include('messaging.urls')),
    path('', include('playground.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

item/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='items_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Items'

    def __str__(self):
        return self.name
    

        

item/forms.py
from django import forms
from .models import Item

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['category', 'name', 'description', 'price', 'image']

        widgets = {
            'category': forms.Select(attrs={'class': 'w-full py-2 px-4'}),
            'name': forms.TextInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Item Name'}),
            'description': forms.Textarea(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Description'}),
            'price': forms.NumberInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Price'}),
            'image': forms.ClearableFileInput(attrs={'class': 'w-full py-2 px-4'}),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'price', 'image', 'is_sold']

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Item Name'}),
            'description': forms.Textarea(
                attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Description'}),
            'price': forms.NumberInput(
                attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Price'}),
            'image': forms.ClearableFileInput(
                attrs={'class': 'w-full py-2 px-4'}),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Item, Category
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm



# Create your views here.
def browse(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False).order_by('-created_at')
    categories = Category.objects.all()

    if category_id:
        items = items.filter(category_id = category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains = query))


    return render(request, 'items/browse.html', {
        'items': items,
        'query' :query, 
        'categories': categories,
        'category_id': int(category_id)

        })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold =False).exclude(pk=item.pk)[0:6]
    return render(request, 'items/detail.html', 
                  {'item': item, 
                   'related_items': related_items,
                   })
 
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:details', pk=item.pk)
    else:
        form = NewItemForm()

    return render(request, 'items/form.html', {'form': form,
                                               'title': 'Create Item',})


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        
        if form.is_valid():
            form.save()

            return redirect('item:details', pk=item.pk)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'items/form.html', {'form': form,
                                               'title': 'Edit Item',})

item/templates/items/browse.html
{% extends 'base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}
    <div class= "pb-6 grid grid-cols-4 gap-6 auto-rows-fr">
        <div class="col-span-1">
            <aside class="w-64 bg-white w-full shadow-md rounded-lg p-4">
            <form method="GET" action="{% url 'item:browse' %}" class="mb-4">
                <input type="text" name="query" placeholder="Search items..." class="border border-gray-300 px-3 py-2 rounded-md w-full" value = "{{ query}}">
                <button type="submit" class="btn btn-outline-success mx-2 my-2 my-sm-0 hover:underline">Search</button>
                    <hr class = "my-6">
                    <p class="text-lg font-semibold mb-4">Filter By Categories</p>
                    <ul>
                        {% for category in categories%}
                        <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                            <a href = "{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}" class="hover:underline"> {{ category.name}} </a>
                        </li>
                        {% endfor %}
                    </ul>
                    
                    <hr class = "my-6">
                    <p class="text-lg font-semibold mb-4">Filter By Categories</p>
                    <ul>
                        <li> 
                            <a href = "{% url 'item:browse' %}" class="mt-2 py-2 px-4 inline-block text-gray-700 hover:underline">Clear Filter</a>
                        </li>  
                    </ul>
            </form>
        </aside>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3 auto-rows-fr">
                
                {% for item in items %}
                    <div class="border rounded-xl shadow-md overflow-hidden flex flex-col">
                        <a href="{% url 'item:details' item.id %}" class="flex flex-col h-full">
                            <div>
                                <p class="text-gray-500 text-sm p-2">{{ item.created_at }}</p>
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" 
                                    class="rounded-t-xl hover:bg-gray-200 w-full h-48 object-contain">
                            </div>
        
                        <div class="p-6 bg-white rounded-b-xl flex-grow flex flex-col justify-between">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: Php {{ item.price }}</p>
                        </div>
                        </a>
                    </div>
                {% endfor %}    
            </div>
        </div> 

    </div>
{% endblock %}

item/templates/items/detail.html
{% extends 'base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3 pb-6 m">
            <img src = "{{ item.image.url }}" class="rounded-xl">
        </div>    
        <div class="col-span-2 p-6 bg-gray-50 rounded-xl ">
            <h2 class="text-2xl">{{ item.name }}</h2>
            <p class="text-gray-500"><strong>Price: Php </strong>{{ item.price }}</p>
            {% if item.description %}
            <p class="text-gray-500">Description: {{ item.description }}</p>
            {% endif %}
            
            <p class="text-gray-500">Category: {{ item.category.name }}</p>
            <p class="text-gray-500">Seller: <a href="#" class = "text-blue-500 hover:text-blue-700">{{ item.created_by.username }}</a></p>
            <p class="text-gray-500">Posted at: {{ item.created_at }}</p>
            {% if request.user == item.created_by %}
                <div class=" text-gray-500 rounded-xl">
                    <p>Added item</p>

                    <a  href="{% url 'item:edit' item.id %}" class="inline-block text-white font-semibold  rounded px-4 py-2 bg-green-500 hover:bg-green-700  ">Edit</a>
                    <a  href=" {% url 'item:delete' item.id %}" class="inline-block text-white font-semibold  rounded px-4 py-2 bg-red-500 hover:bg-red-700  ">Delete</a>
                    
                </div>
            {% endif %}

            <a  href="{% url 'messaging:new' item.id%}" class="text-white font-bold py-2 px-4 rounded mt-6 bg-blue-500 hover:bg-blue-700  ">Contact Seller</a>
            <button onclick="" class="mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Add to Cart</button>
        </div>
    </div>
    
    <div class="mt-6 px-6 py-12 bg-gray-50 rounded-xl">
        <h2 class="mb-12 text-2xl text-center font-semibold">Related Items</h2>

        <div class="grid grid-cols-6 gap-6 auto-rows-fr">
            {% for item in related_items %}
                <div class="border rounded-xl shadow-md overflow-hidden flex flex-col">
                    <a href="{% url 'item:details' item.id %}" class="flex flex-col h-full">
                        <div>
                            <p class="text-gray-500 text-sm p-2">{{ item.created_at }}</p>
                            <img src="{{ item.image.url }}" alt="{{ item.name }}" 
                                class="rounded-t-xl hover:bg-gray-200 w-full h-48 object-contain">
                        </div>
    
                    <div class="p-6 bg-white rounded-b-xl flex-grow flex flex-col justify-between">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: Php {{ item.price }}</p>
                    </div>
                    </a>
                </div>
            {% endfor %}    
        </div>
            
    </div>

{% endblock %}

item/templates/items/form.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="w-1/2 mx-auto p-6 bg-gray-50 rounded-xl">
    
<h1 class='mb-6 text-2xl font-semibold'>{{ title }}</h1>
<form method="POST" action="." enctype="multipart/form-data" class="w-1/2">
    {% csrf_token %}

    
    <div class="mb-4">
        <label for="category" class="block mb-2 text-gray-700">Category:</label>
        {{ form.category }}
    </div>
    <div class="mb-4">
        <label for="name" class="block mb-2 text-gray-700">Item Name:</label>
        {{ form.name }}
    </div>
    <div class="mb-4">
        <label for="description" class="block mb-2 text-gray-700">Description:</label>
        {{ form.description }}
    </div>
    <div class="mb-4">
        <label for="price" class="block mb-2 text-gray-700">Price:</label>
        {{ form.price }}
    </div>
    <div class="mb-4">
        <label for="image" class="block mb-2 text-gray-700">Image:</label>
        {{ form.image }}
        <img id="preview" src="#" alt="Image Preview" class="mt-4 hidden w-fit h-48 object-cover rounded border" />
    </div>
    {# Add JavaScript to handle image preview #}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const imageInput = document.querySelector('input[type="file"]');
            const preview = document.getElementById('preview');
        
            imageInput.addEventListener('change', function () {
                const file = this.files[0];
        
                if (file) {
                    const reader = new FileReader();
        
                    reader.onload = function (e) {
                        preview.setAttribute('src', e.target.result);
                        preview.classList.remove('hidden');
                    }
        
                    reader.readAsDataURL(file);
                } else {
                    preview.setAttribute('src', '#');
                    preview.classList.add('hidden');
                }
            });
        });
        </script>


    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for fields in form %}
            {{ fields.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <button type="submit" class="mt-6 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
</form>
</div>
{% endblock %}