dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path ('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='details'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

messaging/urls.py
from django.urls import path

from .import views
app_name = 'messaging'

urlpatterns = [
    path('new/<int:item_pk>/', views.new_message, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('', views.inbox, name='inbox'),
]

playground/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'playground'
#URL condfiguration
urlpatterns = [
    path('', views.main, name='main'),
    path('contacts/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'login.html', authentication_form = LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

storefront/urls.py
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar  # type: ignore
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),    
    path('items/', include('item.urls')), 
    path('dashboard/', include('dashboard.urls')),
    path('messaging/', include('messaging.urls')),
    path('', include('playground.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

playground/models.py
from django.db import models

# Create your models here.
# Database

playground/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Password', 'data-toggle': 'password'}))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full py-2 px-4', 'placeholder': 'Confirm Password'}))

playground/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import logout

from item.models import Item, Category
from .forms import SignUpForm
# Create your views here.
#request handler


def main(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')
    categories = Category.objects.all()
    return render(request, 'index.html', {
        'items': items, 
        'categories': categories
        })


def contact(request):
    return render(request, 'contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('playground:login')
    else:
        form = SignUpForm()

    return render (request, 'signup.html',{
        'form': form

    })


def userloggedin(request):
    if request.user.is_authenticated == True:
        username = request.user.username
    else:
        return False


def logout_view(request):
        logout(request)
        return redirect('playground:main')

playground/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src = "https://cdn.tailwindcss.com"></script>
    <title>{% block title %} {% endblock %} | Cartify</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200" >
            <a href="{% url 'playground:main' %}" class = "text-xl font-semibold">Cartify</a>
            
                <form class="flex-grow mx-10 max-w-2lg flex">
                    <input class="border border-gray-300 px-3 py-2  rounded-md" type="saerch" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-success mx-2 my-2 my-sm-0" type="submit">Search</button>
                    </form>
           

            <div class="space-x-6">
                <a href="{% url 'playground:main' %}" class="text-gray-500 hover:text-gray-900 font-semibold">Home</a>
                <a href="{% url 'item:new' %}" class="text-gray-500 hover:text-gray-900 font-semibold">Create</a>
                <a href="{% url 'item:browse' %}" class="text-gray-500 hover:text-gray-900 font-semibold" >Browse</a>

                {% if request.user.is_authenticated %}
                <a href="{% url 'messaging:inbox' %}" class="text-gray-500 hover:text-gray-900 font-semibold">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="text-gray-500 hover:text-gray-900 font-semibold" >Dashboard</a>
                {% else %}
                <a href="{% url 'playground:signup' %}" class="text-lg text-blue-500 hover:text-blue-700 font-semibold">Sign Up</a>
                <a href="{% url 'playground:login' %}" class="px-5 py-2 text-lg font-semibold bg-blue-400 text-white rounded-xl hover:bg-blue-600">Login</a>
                {% endif %}

            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
            
        </div>
        
        
        <footer class="px-6 py-6 flex justify-between bg-gray-800">
            <div class = "w-2/3 pr-10">
                <h3 class = "mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-300">
                    Welcome to Cartify, your go-to online marketplace for discovering, buying, and selling a wide range of products with ease. 
                    We connect buyers and sellers in a seamless, secure, and user-friendly environment, offering everything from electronics and 
                    fashion to home essentials and unique handmade items.
                </p>
            </div>
                
                <div class="w-1/4">
                    <h3 class = "mb-5 font-semibold text-gray-400">Menu</h3>
                    <ul class="space-y-2">
                        <li><a href="#" class="text-teal-300 hover:text-teal-100">Home</a></li>
                        <li><a href="{% url 'playground:contact' %}" class="text-teal-300 hover:text-teal-100">Contacts</a></li>
                        <li><a href="#" class="text-teal-300 hover:text-teal-100">Terms and Policy</a></li>
                        <li><a href="#" class="text-teal-300 hover:text-teal-100">Privacy Policy</a></li>
                        <li><a href="{% url 'playground:logout' %}" class="text-teal-300 hover:text-teal-100">Log out</a></li>
                        
                    </ul>

                </div>
            
        </footer>
    </body>
</html>

playground/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contacts{% endblock %}
    
    {% block content %}
        <div class="px-6 py-6">
            <form method="GET" action="" >
                <input type="search" name="search"> 
                <button type="submit"> Search </button>
            </form>
            <h1>This is the contact page</h1>
            {% if name %}
                <h2>Hello, {{ name }}!</h2>
            {% else %}
                <h2>Hello Visitor!</h2>
            {% endif %}
        </div>
    {% endblock %}

playground/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}
    
    {% block content %}
        <div class="mt-6 px-6 py-12 bg-gray-50 rounded-xl">
            <h2 class="mb-12 text-2xl text-center font-semibold">Newest Items</h2>

            <div class="grid grid-cols-6 gap-6 auto-rows-fr">
                
                {% for item in items %}
                    <div class="border rounded-xl shadow-md overflow-hidden flex flex-col">
                        <a href="{% url 'item:details' item.id %}" class="flex flex-col h-full">
                            <div>
                                <p class="text-gray-500 text-sm p-2">{{ item.created_at }}</p>
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" 
                                    class="rounded-t-xl hover:bg-gray-200 w-full h-48 object-contain">
                            </div>
        
                        <div class="p-6 bg-white rounded-b-xl flex-grow flex flex-col justify-between">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: Php {{ item.price }}</p>
                        </div>
                        </a>
                    </div>
                {% endfor %}    
            </div>
                
        </div>
        <div class="mt-6 px-6 py-12 bg-gray-50 rounded-xl">
            <h2 class="mb-12 text-2xl text-center font-semibold">Categories</h2>

            <div class="grid grid-cols-3 gap-10 ">
            {% for category in categories %}
                    <a href="#" class="text-blue-500 hover:text-blue-700"   >

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500 ">{{ category.items.count }}</p>
                        
                
                    </div>
                    </a>
            {% endfor %}
            </div>
        </div>

    {% endblock %}

playground/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="w-1/4 mx-auto p-6 bg-gray-50 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>

        <form method="POST" action=".">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-4">
                <label for="username" class="block mb-2 text-gray-700">Username:</label>
                {{ form.username }}
            </div>
            <div class="mb-4">
                <label for="password" class="block mb-2  text-gray-700">Password:</label>
                {{ form.password }}
            </div>
            
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for fields in form %}
                    {{ fields.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button type="submit" class="mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Login</button>
        
    </div>
{% endblock %}

playground/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="w-1/4 mx-auto p-6 bg-gray-50 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign Up</h1>

        <form method="POST" action=".">
            {% csrf_token %}
            
            <div class="mb-4">
                <label for="username" class="block mb-2 text-gray-700">Username:</label>
                {{ form.username }}
            </div>
            <div class="mb-4">
                <label for="email" class="block mb-2 text-gray-700">Email:</label>
                {{ form.email }}
            </div>
            <div class="mb-4">
                <label for="password1" class="block mb-2  text-gray-700">Password:</label>
                {{ form.password1 }}
            </div>
            <div class="mb-4">
                <label for="password2" class="block mb-2 text-gray-700">Confirm Password:</label>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for fields in form %}
                        {{ fields.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Sign Up</button>
        
    </div>

{% endblock %}